#!/usr/bin/python
# -*- coding: utf-8 -*-

class Student(object):

    def __init__(self, name, score):
        self.name = name
        self.score = score

    def print_score(self):
        print('%s: %s' % (self.name, self.score))

    def get_grade(self):
        if self.score >= 90:
            return 'A'
        elif self.score >= 60:
            return 'B'
        else:
            return 'C'

tangdu = Student('tangdu',11)
liming = Student('liming',22)

tangdu.print_score()
print('得分 = %s' % tangdu.get_grade())
print('获取成员变量属性 = %s' % tangdu.name);
